[package]
name = "tuirealm_derive"
version = "1.0.0"
authors = ["Christian Visintin"]
edition = "2018"
categories = ["command-line-utilities"]
description = "Derive macro for automatically implementing MockComponent for Component"
documentation = "https://docs.rs/tuirealm_derive"
homepage = "https://github.com/veeso/tuirealm_derive"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["tui", "terminal"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/veeso/tuirealm_derive"

[lib]
name = "tuirealm_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"

[dev-dependencies]
#tuirealm = "1.0"
tuirealm = { git = "https://github.com/veeso/tui-realm", branch = "new-api" }

[features]
